export const ADD_TASK = 'TODO_LIST/TODO_LIST/ADD_TASK';
export const DONE_TASK = 'TODO_LIST/TODO_LIST/DONE_TASK';
export const DEL_TASK = 'TODO_LIST/TODO_LIST/DEL_TASK';
export const IMPORTANT_TASK = 'TODO_LIST/TODO_LIST/IMPORTANT_TASK';
export const EDIT_TASK = 'TODO_LIST/TODO_LIST/EDIT_TASK';
export const EDIT_MODE = 'TODO_LIST/TODO_LIST/EDIT_MODE';

export const CHANGED_SEARCH_INPUT = 'TODO_LIST/TODO_LIST/CHANGED_SEARCH_INPUT';
export const CHANGED_ADD_INPUT = 'TODO_LIST/TODO_LIST/CHANGED_ADD_INPUT';
export const CHANGED_FILTER = 'TODO_LIST/TODO_LIST/CHANGED_FILTER';

export const SET_TASKS = 'TODO_LIST/TODO_LIST/SET_TASKS';
export const SET_STATUS = 'TODO_LIST/TODO_LIST/SET_STATUS';

export const STATUSES_APP = {
	NOT_INIT: 'NOT_INITIALIZED',
	IN_PROGRESS_INIT: 'IN_PROGRESS_INIT',
	IN_PROGRESS_EDIT: 'IN_PROGRESS_EDIT',
	IN_PROGRESS_APP: 'IN_PROGRESS_APP',
	SUCCESS: 'SUCCESS',
	ERROR: 'ERROR'
};